# Generated by Django 4.2.2 on 2023-06-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('company', models.CharField(db_index=True, max_length=100)),
                ('trade_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('SPLIT', 'SPLIT')], db_index=True, max_length=10)),
                ('quantity', models.IntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'indexes': [models.Index(fields=['id'], name='transaction_id_6e65d0_idx')],
            },
        ),
    ]
